defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  host: localhost

development:
  <<: *defaults
  database: saywhat_dev
  username: root
  password: 

test:
  <<: *defaults
  database: saywhat_test
  username: root
  password:

production:
  <<: *defaults
  database: saywhat_production