defaults: &defaults
  adapter: mysql2
  host: localhost

development:
  <<: *defaults
  database: saywhat_dev
  username: root
  password: root

test:
  <<: *defaults
  database: saywhat_test
  username: root
  password: root