reasons:
  groups:
    - name: "age"
      short_text: "Incorrect age group"
      email_text: "Unfortunately, at this time Say What! is only open to Junior High and High School groups in Texas."
    - name: "organization"
      short_text: "Not a youth focused group"
      email_text: "Say What! is currently open to groups of high school and junior high age students who are working to combat the effects of tobacco use in their school and/or community. While we encourage them to seek out community partnerships with agencies that have the same goal, the online group collaboration site is an area for the young people to work together on their projects."
    - name: "missing"
      short_text: "Unclear focus"
      email_text: "It was unclear what your group's focus is. Say What! is currently open to groups of high school and junior high age students who are working to combat the effects of tobacco use in their school and/or community."
    - name: "youth"
      short_text: "Youth sponsor"
      email_text: "Each group registered on the SayWhat! site must have an adult sponsor associated with it. Please have your adult sponsor complete the group request form."
  grants:
    - name: "curriculum"
      short_text: "Incorrect curriculum"
      email_text: "The funding can not be used to purchase or implement specific curriculum or classroom materials or for adults to provide presentations to youth."
    - name: "youth"
      short_text: "Not enough youth involvement"
      email_text: "The projects must be youth-led and demonstrate a significant amount of youth engagement and involvement."
    - name: "funds"
      short_text: "Scholarship Funds"
      email_text: "Mini-grant funds cannot be used for scholarship purposes."
    - name: "timeline"
      short_text: "Incorrect Timeline"
      email_text: "Your proposed project does not occur within the time frame allowed by this round of funding."