# Notifications Database
notifications:
  production:
    host: localhost
    database: saywhat_notifications

  development:
    host: localhost
    database: saywhat_notifications

  test:
    host: localhost
    database: saywhat_test