# Themes:
#  
# Allows you to swap themes without changing the core-system files
# Requires the use of SASS but stylesheets can be written in plain css

# The name of your theme folder
theme: "default"

# The name of your stylesheet folder
# Must contain an "application" stylesheet that either:
#  - Contains all your styles
#  - Imports other stylesheets
# This is what is called in the template HEAD section
stylesheets: "css"

# The name of your javascripts folder
# The base system functions are imported automatically
# You already have access to the latest version of jQuery
# Only include function you would like to add that don't currently exists
# Made to complement custom themes
javascripts: "js"

# The name of your images folder
# This is where your images from your stylesheet are served from.
# EX: background: src('/img/example-file.png)
images: "img"

# Toggle for displaying static resources page
static_resources: false